<?php

declare(strict_types=1);

namespace Sediment\Generator;

use Sediment\Analyzer\Finding;
use Sediment\Analyzer\WordPressCore;

/**
 * Generates a syntactically valid `uninstall.php` that removes what a plugin
 * leaves behind (M13).
 *
 * Safety first: only artifacts that are `verified` or `resolved`, not already
 * cleaned, and not WordPress core are emitted. `pattern` and `dynamic` keys are
 * never generated — deleting on a guess is the failure this project exists to
 * avoid. The `{prefix}` token is rebuilt from `$wpdb->prefix` wherever it
 * appears, for every artifact type, never a hardcoded prefix.
 */
final class UninstallGenerator
{
    private const PREFIX_TOKEN = '{prefix}';

    /**
     * @param list<Finding> $findings
     */
    public function generate(array $findings, string $pluginName = 'this plugin'): string
    {
        $options = [];
        $siteOptions = [];
        $tables = [];
        $cron = [];
        $transients = [];   // key => delete function
        $meta = [];         // key => meta object type
        $roles = [];
        $actions = [];
        $content = [];      // reported as a comment, never deleted

        foreach ($findings as $finding) {
            if (!$this->isDeletable($finding)) {
                continue;
            }

            /** @var string $key */
            $key = $finding->key;

            match ($finding->type) {
                'option'    => $this->isSiteScoped($finding) ? $siteOptions[$key] = true : $options[$key] = true,
                'table'     => $tables[$key] = true,
                // An event scheduled with arguments is not removed by
                // wp_clear_scheduled_hook(), so it needs the broader call. If the
                // same hook is scheduled both ways, the broader call wins.
                'cron'      => $cron[$key] = ($finding->hasArgs || ($cron[$key] ?? null) === 'wp_unschedule_hook')
                    ? 'wp_unschedule_hook'
                    : 'wp_clear_scheduled_hook',
                'transient' => $transients[$key] = $this->isSiteScoped($finding) ? 'delete_site_transient' : 'delete_transient',
                'post_meta', 'user_meta', 'term_meta', 'comment_meta' => $meta[$key] = str_replace('_meta', '', $finding->type),
                'role'      => $roles[$key] = true,
                'action'    => $actions[$key] = true,
                'post_type', 'taxonomy', 'directory', 'rewrite_rule' => $content[$key] = $finding->type,
                default     => null,
            };
        }

        foreach ([&$options, &$siteOptions, &$tables, &$cron, &$transients, &$meta, &$roles, &$actions, &$content] as &$group) {
            ksort($group);
        }
        unset($group);

        return $this->render($pluginName, $options, $siteOptions, $tables, $cron, $transients, $meta, $roles, $actions, $content);
    }

    private function isDeletable(Finding $finding): bool
    {
        return $finding->key !== null
            && $finding->isConfident()
            && $finding->cleaned !== true
            && !WordPressCore::isCore($finding);
    }

    /**
     * Network options and site options are the same rows; delete_site_option
     * delegates to delete_network_option, so both are removed the site way.
     */
    private function isSiteScoped(Finding $finding): bool
    {
        return str_contains($finding->function, 'site') || str_contains($finding->function, 'network');
    }

    /**
     * @param array<string, true> $options
     * @param array<string, true> $siteOptions
     * @param array<string, true> $tables
     * @param array<string, string> $cron hook => clearing function
     * @param array<string, string> $transients
     * @param array<string, string> $meta key => object type (post|user|term|comment)
     * @param array<string, true> $roles
     * @param array<string, true> $actions Action Scheduler hooks
     * @param array<string, string> $content artifacts reported as a comment only
     */
    private function render(string $pluginName, array $options, array $siteOptions, array $tables, array $cron, array $transients, array $meta = [], array $roles = [], array $actions = [], array $content = []): string
    {
        $needsWpdb = $tables !== [] || $this->anyPrefixed([
            ...array_keys($options), ...array_keys($siteOptions), ...array_keys($cron),
            ...array_keys($transients), ...array_keys($meta), ...array_keys($roles), ...array_keys($actions),
        ]);

        $lines = [
            '<?php',
            '',
            '/**',
            ' * Uninstall routine generated by Sediment for ' . $this->safeName($pluginName) . '.',
            ' *',
            ' * Removes the data this plugin leaves behind. Review before shipping:',
            ' * Sediment only emits artifacts it attributed with high confidence, so',
            ' * check the scan\'s coverage report for anything it could not resolve.',
            ' */',
            '',
            "if (!defined('WP_UNINSTALL_PLUGIN')) {",
            '    exit;',
            '}',
        ];

        if ($needsWpdb) {
            $lines[] = '';
            $lines[] = 'global $wpdb;';
        }

        if ($options !== [] || $siteOptions !== []) {
            $lines[] = '';
            $lines[] = '// Options';
            foreach (array_keys($options) as $key) {
                $lines[] = 'delete_option(' . $this->keyExpression($key) . ');';
            }
            foreach (array_keys($siteOptions) as $key) {
                $lines[] = 'delete_site_option(' . $this->keyExpression($key) . ');';
            }
        }

        if ($tables !== []) {
            $lines[] = '';
            $lines[] = '// Custom tables';
            foreach (array_keys($tables) as $key) {
                $lines[] = '$table = ' . $this->keyExpression($key) . ';';
                $lines[] = '$wpdb->query("DROP TABLE IF EXISTS `{$table}`");';
            }
        }

        if ($cron !== []) {
            $lines[] = '';
            $lines[] = '// Scheduled events';
            foreach ($cron as $hook => $function) {
                $lines[] = $function . '(' . $this->keyExpression($hook) . ');';
            }
        }

        if ($transients !== []) {
            $lines[] = '';
            $lines[] = '// Transients';
            foreach ($transients as $key => $function) {
                $lines[] = $function . '(' . $this->keyExpression($key) . ');';
            }
        }

        if ($meta !== []) {
            $lines[] = '';
            $lines[] = '// Metadata (removed across every object)';
            foreach ($meta as $key => $objectType) {
                $lines[] = $objectType === 'post'
                    ? 'delete_post_meta_by_key(' . $this->keyExpression($key) . ');'
                    : sprintf("delete_metadata('%s', 0, %s, '', true);", $objectType, $this->keyExpression($key));
            }
        }

        if ($roles !== []) {
            $lines[] = '';
            $lines[] = '// Roles (this also drops the capabilities they were created with)';
            foreach (array_keys($roles) as $role) {
                $lines[] = 'remove_role(' . $this->keyExpression($role) . ');';
            }
        }

        if ($actions !== []) {
            $lines[] = '';
            $lines[] = '// Action Scheduler jobs (the library may already be gone, so guard the call)';
            $lines[] = "if (function_exists('as_unschedule_all_actions')) {";
            foreach (array_keys($actions) as $hook) {
                $lines[] = '    as_unschedule_all_actions(' . $this->keyExpression($hook) . ');';
            }
            $lines[] = '}';
        }

        if ($content !== []) {
            // Deleting posts, terms, or an upload directory destroys user data,
            // and flushing rewrite rules is the site's call. An uninstall routine
            // must not do any of it silently — report and let a human decide.
            $lines[] = '';
            $lines[] = '// This plugin also leaves the following behind. They are intentionally NOT';
            $lines[] = '// removed here, because doing so could destroy data you want to keep:';
            foreach ($content as $name => $type) {
                // The name comes from the scanned plugin's own source. A newline
                // inside it would end this comment early and turn whatever
                // follows into live code in a file people run — flatten it.
                $lines[] = sprintf('//   - %s "%s"', str_replace('_', ' ', $type), str_replace(["\r", "\n"], ' ', $name));
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Build a PHP expression for a key, rebuilding {prefix} from $wpdb->prefix
     * wherever it appears: "{prefix}logs" -> $wpdb->prefix . 'logs'.
     */
    private function keyExpression(string $key): string
    {
        if (!str_contains($key, self::PREFIX_TOKEN)) {
            return var_export($key, true);
        }

        $expression = [];
        foreach (explode(self::PREFIX_TOKEN, $key) as $index => $part) {
            if ($index > 0) {
                $expression[] = '$wpdb->prefix';
            }
            if ($part !== '') {
                $expression[] = var_export($part, true);
            }
        }

        return implode(' . ', $expression);
    }

    /**
     * @param list<string> $keys
     */
    private function anyPrefixed(array $keys): bool
    {
        foreach ($keys as $key) {
            if (str_contains($key, self::PREFIX_TOKEN)) {
                return true;
            }
        }

        return false;
    }

    private function safeName(string $name): string
    {
        // Keep the docblock intact and printable.
        return trim(str_replace(['*/', "\n", "\r"], ' ', $name)) ?: 'this plugin';
    }
}
