<?php

declare(strict_types=1);

namespace Sediment\Generator;

use Sediment\Analyzer\Finding;
use Sediment\Analyzer\WordPressCore;

/**
 * Generates a syntactically valid `uninstall.php` that removes what a plugin
 * leaves behind (M13).
 *
 * Safety first: only artifacts that are `verified` or `resolved`, not already
 * cleaned, and not WordPress core are emitted. `pattern` and `dynamic` keys are
 * never generated — deleting on a guess is the failure this project exists to
 * avoid. The `{prefix}` token is rebuilt from `$wpdb->prefix` wherever it
 * appears, for every artifact type, never a hardcoded prefix.
 */
final class UninstallGenerator
{
    private const PREFIX_TOKEN = '{prefix}';

    /**
     * @param list<Finding> $findings
     */
    public function generate(array $findings, string $pluginName = 'this plugin'): string
    {
        $options = [];
        $siteOptions = [];
        $tables = [];
        $cron = [];
        $transients = [];   // key => delete function

        foreach ($findings as $finding) {
            if (!$this->isDeletable($finding)) {
                continue;
            }

            /** @var string $key */
            $key = $finding->key;

            match ($finding->type) {
                'option'    => $this->isSiteScoped($finding) ? $siteOptions[$key] = true : $options[$key] = true,
                'table'     => $tables[$key] = true,
                'cron'      => $cron[$key] = true,
                'transient' => $transients[$key] = $this->isSiteScoped($finding) ? 'delete_site_transient' : 'delete_transient',
                default     => null,
            };
        }

        ksort($options);
        ksort($siteOptions);
        ksort($tables);
        ksort($cron);
        ksort($transients);

        return $this->render($pluginName, $options, $siteOptions, $tables, $cron, $transients);
    }

    private function isDeletable(Finding $finding): bool
    {
        return $finding->key !== null
            && $finding->isConfident()
            && $finding->cleaned !== true
            && !WordPressCore::isCore($finding);
    }

    private function isSiteScoped(Finding $finding): bool
    {
        return str_contains($finding->function, 'site');
    }

    /**
     * @param array<string, true> $options
     * @param array<string, true> $siteOptions
     * @param array<string, true> $tables
     * @param array<string, true> $cron
     * @param array<string, string> $transients
     */
    private function render(string $pluginName, array $options, array $siteOptions, array $tables, array $cron, array $transients): string
    {
        $needsWpdb = $tables !== [] || $this->anyPrefixed([...array_keys($options), ...array_keys($siteOptions), ...array_keys($cron), ...array_keys($transients)]);

        $lines = [
            '<?php',
            '',
            '/**',
            ' * Uninstall routine generated by Sediment for ' . $this->safeName($pluginName) . '.',
            ' *',
            ' * Removes the data this plugin leaves behind. Review before shipping:',
            ' * Sediment only emits artifacts it attributed with high confidence, so',
            ' * check the scan\'s coverage report for anything it could not resolve.',
            ' */',
            '',
            "if (!defined('WP_UNINSTALL_PLUGIN')) {",
            '    exit;',
            '}',
        ];

        if ($needsWpdb) {
            $lines[] = '';
            $lines[] = 'global $wpdb;';
        }

        if ($options !== [] || $siteOptions !== []) {
            $lines[] = '';
            $lines[] = '// Options';
            foreach (array_keys($options) as $key) {
                $lines[] = 'delete_option(' . $this->keyExpression($key) . ');';
            }
            foreach (array_keys($siteOptions) as $key) {
                $lines[] = 'delete_site_option(' . $this->keyExpression($key) . ');';
            }
        }

        if ($tables !== []) {
            $lines[] = '';
            $lines[] = '// Custom tables';
            foreach (array_keys($tables) as $key) {
                $lines[] = '$table = ' . $this->keyExpression($key) . ';';
                $lines[] = '$wpdb->query("DROP TABLE IF EXISTS `{$table}`");';
            }
        }

        if ($cron !== []) {
            $lines[] = '';
            $lines[] = '// Scheduled events';
            foreach (array_keys($cron) as $hook) {
                $lines[] = 'wp_clear_scheduled_hook(' . $this->keyExpression($hook) . ');';
            }
        }

        if ($transients !== []) {
            $lines[] = '';
            $lines[] = '// Transients';
            foreach ($transients as $key => $function) {
                $lines[] = $function . '(' . $this->keyExpression($key) . ');';
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Build a PHP expression for a key, rebuilding {prefix} from $wpdb->prefix
     * wherever it appears: "{prefix}logs" -> $wpdb->prefix . 'logs'.
     */
    private function keyExpression(string $key): string
    {
        if (!str_contains($key, self::PREFIX_TOKEN)) {
            return var_export($key, true);
        }

        $expression = [];
        foreach (explode(self::PREFIX_TOKEN, $key) as $index => $part) {
            if ($index > 0) {
                $expression[] = '$wpdb->prefix';
            }
            if ($part !== '') {
                $expression[] = var_export($part, true);
            }
        }

        return implode(' . ', $expression);
    }

    /**
     * @param list<string> $keys
     */
    private function anyPrefixed(array $keys): bool
    {
        foreach ($keys as $key) {
            if (str_contains($key, self::PREFIX_TOKEN)) {
                return true;
            }
        }

        return false;
    }

    private function safeName(string $name): string
    {
        // Keep the docblock intact and printable.
        return trim(str_replace(['*/', "\n", "\r"], ' ', $name)) ?: 'this plugin';
    }
}
